### PR TITLE
[WIP] 2.0.0-dev.1

### LINKED ISSUE #14: glTF 2.0: Please remove warning for empty node.
First at all, thx a lot for this. The validator did help me to remove some errors and warnings. So back to this issue:

An empty node is valid in glTF 2.0. It is even mentioned on the specification site:
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#scenes

At first, I wanted to suggest to convert this output from a `warning` to an `optimization ` but I think even empty nodes do make sense, e.g. having an empty node, where in the 3D game engine a dynamic object like a weapon can be placed.

So, as it is valid, it should not cause any warnings.

```
"warnings": {
            "NODE_EMPTY": [
                {
                    "type": "NODE_EMPTY",
                    "path": "#/nodes/3",
                    "message": "Empty node encountered."
                }
            ]
        },
```

### PR DESCRIPTION
**Pull request by lexaknyazev**
This should fix #14, #24, and #27. See [changelog](https://github.com/KhronosGroup/glTF-Validator/blob/0c6bbd005037058ef16ea9830c63ea81dd109992/CHANGELOG.md) for details.

/cc @emackey @donmccurdy @javagl

### CODE REVIEW

**Comment by lexaknyazev** [comment]
Live demo:
https://lexaknyazev.github.io/glTF-Validator/

**Comment by emackey** [comment]
I don't know Dart well enough to do a complete code review, but nothing sticks out as egregious here.  I tested the live demo link above, and it looks like the output matches the changes discussed in other issues here.

My one comment is actually with *valid* models.  The `issues` block is completely missing for valid models, is this the desired behavior?  Would it be better to have something like this:

```
        "issues": {
            "numErrors": 0,
            "numWarnings": 0,
            "numInfos": 0,
            "numHints": 0,
            "messages": [
            ]
        },
```

It doesn't matter to my extension, just asking what is better for the community in general.

**Comment by lexaknyazev** [comment]
> I don't know Dart well enough to do a complete code review...

I'm looking for feature-wise feedback: report format, updated JS API.

`issues` object  is missing for valid models, but it could be there if that's needed.

**Comment by emackey** [comment]
> `issues` object is missing for valid models, but it could be there if that's needed.

Any thoughts on this?  @javagl @zellski @donmccurdy @AurL @sbtron

**Comment by donmccurdy** [comment]
Slight preference for keeping `issues` to report all zeroes, but either way is OK I think.

**Comment by lexaknyazev** [comment]
@donmccurdy @emackey 
Do you prefer an empty `messages` array, or we can write only `num*` zeros:
```json
{
    "numErrors": 0,
    "numWarnings": 0,
    "numInfos": 0,
    "numHints": 0
}

**Comment by emackey** [comment]
> Do you prefer an empty messages array, or we can write only num* zeros

I think the advantage to keeping this section would be to preserve the same shape of the results output object.  So if the numbers are there, I would expect the empty array to be there.  In other projects I've written a lot of code that has to perform double-checks, "if this array exists, and the array has non-zero length..." and I think it's cleaner to just expect the array to exist even if it's empty.

**Comment by lexaknyazev** [comment]
Requested format change has been implemented. Live demo updated.

**Comment by lexaknyazev** [comment]
@emackey @zellski @donmccurdy 
I'm going to change JS API to move last three arguments (`maxIssues`, `ignoredIssues`, and `severityOverrides`) into a single `options` object. This would allow extending validation options without breaking API.

**Current:**
```javascript
validator.validateBytes(
    id,
    data,
    handler,
    10,
    [ 'UNSUPPORTED_EXTENSION' ],
    {
        ACCESSOR_INDEX_TRIANGLE_DEGENERATE: 0
    });
```
**Proposed:**
```javascript
validator.validateBytes(
    id,
    data,
    handler,
    {
        maxIssues: 10,
        ignoredIssues: [ 'UNSUPPORTED_EXTENSION' ],
        severityOverrides: {
            ACCESSOR_INDEX_TRIANGLE_DEGENERATE: 0
        }
    });
```

Any objections?

**Comment by zellski** [comment]
LGTM. This approach is nearly always favourable as complexity increases
IMO.

**Comment by donmccurdy** [comment]
+1 for the `options` object.

**Comment by lexaknyazev** [comment]
Please test updated glTF-Validator build. If everything's fine I'll merge and tag it.
Live demo: https://lexaknyazev.github.io/glTF-Validator/

**Comment by lexaknyazev** [comment]
@emackey 
Do you want to check VSCode integration with this branch before tagging? 
Otherwise I'll merge it and release `2.0.0-dev.1.0`.

**Comment by emackey** [comment]
> Do you want to check VSCode integration with this branch before tagging?

Not for a `-dev` release, I think the expectation is API breakage there with every revision (right?)  If you want me to I can try to get that tested within a day or two, but I don't expect any show-stoppers, may as well just publish a dev release and test from there.

**Pull request merged**
