### PR TITLE
Include docs in archives & update notices

### PR DESCRIPTION
**Pull request by lexaknyazev**
This PR updates 3rd-party licenses and ensures that all required docs are included in the generated archives.

@emackey 
Do we need to re-publish the npm package?

### CODE REVIEW

**Comment by emackey** [comment]
@lexaknyazev I suspect it's easier to bump the version number than it is to try to edit a published version on npm.

**Comment by lexaknyazev** [comment]
The already published npm package is immutable. Do you think we should issue a new one just for this change?

**Comment by lexaknyazev** [comment]
I think these are our options:
- Leave the version as-is
- Bump to `2.0.0-dev.3.5`
- Append build metadata like `2.0.0-dev.3.4+1`

For the last two options we may choose to release a new npm package or to wait until the next release.

**Comment by emackey** [comment]
I don't have a strong opinion.  May as well bump to 3.5, just to keep the version numbering simple.

**Comment by lexaknyazev** [comment]
PTAL

**Review by emackey — APPROVED** [review]

**Comment by emackey** [comment]
@lexaknyazev Awesome.  Let me know when the GitHub release tag is up, thanks!

**Comment by lexaknyazev** [comment]
The release tag is up. This time, we also ship a precompiled binary for macOS and a copy of the hosted drag-n-drop tool in addition to Windows and Linux builds.

**Comment by emackey** [comment]
This is published to [NPM](https://www.npmjs.com/package/gltf-validator) now.

**Pull request merged**
