### PR TITLE
2.0.0-dev.2.3

### PR DESCRIPTION
**Pull request by lexaknyazev**
* Fixed an NPM package regression caused by the new building process.
* Changed `INTEGER_WRITTEN_AS_FLOAT` default severity to Warning.
* Changed `UNUSED_OBJECT` default severity to Info.
* Fixed handling of GLB assets with buffers with broken URIs.

### CODE REVIEW

**Comment by lexaknyazev** [comment]
@donmccurdy Could you check viewer build integration so that we can merge this?

**Comment by donmccurdy** [comment]
Getting errors trying to build this:

```
$ pub run grinder npm

grinder running issues npm-release npm

issues
  Total number of issues: 128

npm-release
  /Users/donmccurdy/bin/pub run build_runner build --delete-conflicting-outputs --output node:build/node --release

ProcessException: No such file or directory
  Command: /Users/donmccurdy/bin/pub run build_runner build --delete-conflicting-outputs --output node:build/node --release
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:485)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:631)
#2      Process.runSync (dart:io-patch/process_patch.dart:66)
#3      run (package:grinder/src/run.dart:29:34)
#4      Pub.run (package:grinder/grinder_sdk.dart:241:12)
#5      _runBuild (file:///Users/donmccurdy/Documents/Projects/valid2/tool/grind.dart:209:7)
#6      _npmBuild (file:///Users/donmccurdy/Documents/Projects/valid2/tool/grind.dart:129:3)
#7      npmRelease (file:///Users/donmccurdy/Documents/Projects/valid2/tool/grind.dart:121:3)
```

**Comment by lexaknyazev** [comment]
@donmccurdy Does `/Users/donmccurdy/bin/pub` point to a valid executable? Looks like something's wrong with SDK location.

**Comment by lexaknyazev** [comment]
I've checked `browserify` workflow, and it seems to work fine.

**Comment by emackey** [comment]
Published to npm.

**Comment by donmccurdy** [comment]
Looks good, thanks!

**Pull request merged**
