### PR TITLE
2.0.0-dev.1.6

### PR DESCRIPTION
**Pull request by lexaknyazev**
See https://github.com/AnalyticalGraphicsInc/gltf-vscode/issues/69.

### CODE REVIEW

**Comment by emackey** [comment]
I tried to fake this out by putting a literal `%20` in a filename, and `%2520` in the glTF URI, to test for double-decode.  Still works 😄

**Comment by donmccurdy** [comment]
Had a validity question about this; see comment in https://github.com/AnalyticalGraphicsInc/gltf-vscode/issues/69

**Comment by emackey** [comment]
It seems like this change is still needed, to work with spaces at all.  It supports both encoded and non-encoded spaces.

**Comment by lexaknyazev** [comment]
Here're examples of validator's behavior:
- `space name?param=value` => `space%20name?param=value` (only the path segment was normalized)
- `space%20name?param=value space` => `space%20name?param=value%20space` (only the query segment was normalized)
- `space%3Fname?param=value` => `space%3Fname?param=value` (no change)

**Comment by lexaknyazev** [comment]
For now, this PR fixes drag-n-drop validator and updates JS example code. We may want to have something more valuable before issuing a new release (e.g. fixing #56).

**Comment by donmccurdy** [comment]
Sounds good. 👍

**Comment by emackey** [comment]
👍

**Comment by emackey** [comment]
I built this and confirmed it fixes the issue I saw in VSCode.

**Comment by lexaknyazev** [comment]
Should we update changelog?

**Comment by emackey** [comment]
Yep

**Comment by lexaknyazev** [comment]
@emackey Please review changelog's language.

**Comment by emackey** [comment]
Looks good 👍

**Comment by emackey** [comment]
Published `gltf-validator@2.0.0-dev.1.6` to npm.

**Pull request merged**
