### PR TITLE
Version 2.0.0-dev.3.8

### LINKED ISSUE #182: Check "All primitives MUST have the same number of morph targets"
The spec says

> All primitives **MUST** have the same number of morph targets in the same order.

I believe that means this should be invalid

```json
"primitives" : [
  {
    "attributes" : {
      "POSITION" : 0
    },
    "indices" : 1,
    "material" : 0
  },
  {
    "attributes" : {
      "POSITION" : 3
    },
    "indices" : 4,
    "material" : 1,
    "targets" : [
      {
        "POSITION" : 5
      }
    ]
  }
],
```

[Example file](https://github.com/KhronosGroup/glTF-Validator/files/8596714/MorphTargetExample.zip)

It passes validation when using https://github.khronos.org/glTF-Validator/ though.

### LINKED ISSUE #186: Volume thickness vs. doubleSided
A suggestion for an additional validation of `KHR_materials_volume`:

When `thicknessFactor` is nonzero, the polygon mesh is [expected to be closed, manifold volume](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_volume#extending-materials) of material.  Generally this implies that `doubleSided` should be `false` for meshes using such a material.

It may be too expensive to add a full manifold mesh test in here just for this, but issuing a warning on the use of `doubleSided` might be a good idea.

### PR DESCRIPTION
**Pull request by lexaknyazev**
### New Features

* Added support for `KHR_materials_iridescence` extension. Added:
  * `KHR_MATERIALS_IRIDESCENCE_THICKNESS_RANGE_INVALID` error;
  * `KHR_MATERIALS_IRIDESCENCE_THICKNESS_RANGE_WITHOUT_TEXTURE` info;
  * `KHR_MATERIALS_IRIDESCENCE_THICKNESS_TEXTURE_UNUSED` info.

* Added `KHR_MATERIALS_VOLUME_DOUBLE_SIDED` warning (fixes #186).

* Added new vendor prefixes.

### Bugfixes

* Fixed inconsistent handling of meshes with morphed and non-morphed primitives (fixes #182).

### CODE REVIEW

**Comment by lexaknyazev** [comment]
> The support for the `KHR_materials_iridescence` extension is not (yet) listed in the main README 'Extensions validation'

Fixed.

**Review by emackey — APPROVED** [review]
Built and tested.  Looks good!

**Comment by emackey** [comment]
Published to npm.

**Comment by emackey** [comment]
This is now available in VSCode glTF Tools v2.3.16.

**Pull request merged**
