### PR TITLE
2.0.0-dev.1.8

### PR DESCRIPTION
**Pull request by lexaknyazev**
The plan is to implement remaining skinning checks as soon as the spec converges on them:
- Validity of joint indices
- Sum of weights per vertex (normalization)
- Order of weights when an asset uses more than 4 influences.
- Hierarchy limits

In the meantime, 
- the validator reports only summary on accessor values that violate declared bounds.
/cc @emackey @donmccurdy .

### CODE REVIEW

**Comment by donmccurdy** [comment]
What was the "hierarchy limits" issue? Having joints outside the skeleton root's tree?

**Comment by lexaknyazev** [comment]
> What was the "hierarchy limits" issue? Having joints outside the skeleton root's tree?

This ^ and skinned mesh with node transforms. 

Exact rules and severities TBD.

**Comment by emackey** [comment]
Generally this looks good to me.  I didn't try it in VSCode but I like the concept.  Sounds like this may still be WIP, let us know when it's ready for final review, thanks.

**Comment by lexaknyazev** [comment]
I hope that the spec will converge  those skinning questions soon. In the meantime, feel free to request additional changes.

**Comment by lexaknyazev** [comment]
@emackey @donmccurdy Let's merge this to keep pace.

**Comment by donmccurdy** [comment]
Sounds good!

**Comment by emackey** [comment]
Version `2.0.0-dev.1.8` is now published to npm.

**Comment by emackey** [comment]
The glTF-VSCode extension now has this update in version 2.1.10.

**Comment by donmccurdy** [comment]
Updated https://gltf-viewer.donmccurdy.com/ as well. :)

**Pull request merged**
