### PR TITLE
Validation issues review

### PR DESCRIPTION
**Pull request by donmccurdy**
Looks good!

One error I wasn't sure about, and didn't change in the PR:

> Unexpected extension object for this extension.

^What does this mean? Perhaps some extra information could be added to this message.

Also note that I changed one of the error names: `INTEGER_WRITTEN_AS_FLOAT`. Not sure if that needs to be updated anywhere outside of this file.

### CODE REVIEW

**Comment by lexaknyazev** [comment]
>> Unexpected extension object for this extension.

> ^What does this mean? Perhaps some extra information could be added to this message.

Consider this:
```json
{
    "asset": {
        "version": "2.0"
    },
    "extensionsUsed": [
        "KHR_materials_pbrSpecularGlossiness"
    ],
    "nodes": [
        {
            "extensions": {
                "KHR_materials_pbrSpecularGlossiness": {}
            }
        }
    ]
}
```

Maybe message / code could be improved.

**Comment by donmccurdy** [comment]
Even with that code snippet I'm not sure what the error means 😄

Is the warning saying the material extension doesn't belong on a node entry? Or that _empty_ extension objects are bad?

**Comment by lexaknyazev** [comment]
This:
> the material extension doesn't belong on a node entry

**Comment by lexaknyazev** [comment]
Empty object is fine for that particular extension.

**Comment by donmccurdy** [comment]
I see. Perhaps `Unexpected location for this extension.`, then. Adjusted PR.

**Comment by lexaknyazev** [comment]
Should `code` be updated as well?

**Comment by donmccurdy** [comment]
I think UNEXPECTED_EXTENSION_OBJECT is fine. The error wording could also be `Unexpected extension object for this location.` and that would be clear as well.

**Pull request merged**
